plugin: aws_ec2

aws_access_key: redacted
aws_secret_key: redacted

regions:
- ap-southeast-1

strict: False

filters:
  tag:Application: weather
  instance-state-name: running

keyed_groups:
- key: tags["Application"]
  prefix: application

hostnames:
- ip-address
- dns-name
- tag:Name