apiVersion: v1
kind: Secret
metadata:
  name: jenkins-envar
  namespace: jenkins-build
type: Opaque
data:
  jenkins-user: YWRtaW4=
  jenkins-pass: YWRtaW4=
  jenkins-email-admin: ZXIubXVzdGhvZmFAZ21haWwuY29t
  jenkins-url: aHR0cDovL2plbmtpbnMuamVua2lucy1idWlsZDo4MDgwLw==
